### ISSUE TITLE
Administrador de la configuración

### ISSUE THREAD

**Issue by Felipeceballos12** [Felipeceballos12/StartpApp#6]
Crear una carpeta compartida para el equipo, donde puedan ir publicando la información del proyecto y dar permisos de edición a todos los integrantes.

**Comment by Rudarkia** [comment]
Se crea una carpeta compartida para el equipo, dándole permisos de edición a todos los integrantes del Equipo.
https://drive.google.com/drive/folders/1sedNpIPpKomhLQF4S1YQ-6uX8OVMeYvr?usp=sharing
