### ISSUE TITLE
Tester

### ISSUE THREAD

**Issue by Felipeceballos12** [Felipeceballos12/StartpApp#9]
Buscar por lo menos dos enlaces de páginas donde se presenten estándares o buenas prácticas de codificación en C#. Publicar los enlaces en un documento en la carpeta compartida.

**Comment by Rudarkia** [comment]
Se realiza la búsqueda de dos enlaces de páginas donde se presenten estándares o buenas prácticas de codificación en C#, realizando su publicación de los enlaces en un documento en la carpeta compartida.

https://docs.google.com/document/d/1JRHNxOofQiWPhQUXUSEe2GEqopyDJIwT/edit?usp=sharing&ouid=113972991806350773351&rtpof=true&sd=true
